repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
      - id: poetry-check
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format .
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: poetry run ruff . --fix
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        language: system
      - id: pytest
        name: pytest
        entry: poetry run pytest tests
        language: system